# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-09-11 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KBCache',
            fields=[
                ('articleid', models.IntegerField(primary_key=True, serialize=False)),
                ('contents', models.TextField()),
                ('contentstext', models.TextField()),
                ('subject', models.TextField()),
                ('dateline', models.DateTimeField()),
                ('attachments', models.TextField(blank=True, null=True)),
                ('viewcount', models.IntegerField(default=0)),
                ('lastupdate', models.DateTimeField(db_index=True)),
            ],
            options={
                'verbose_name': 'Articolo Knowledge Base di Kayako',
                'verbose_name_plural': 'Articoli Knowledge Base di Kayako',
            },
        ),
        migrations.CreateModel(
            name='RestCache',
            fields=[
                ('request', models.TextField(primary_key=True, serialize=False)),
                ('response', models.TextField()),
                ('creazione', models.DateTimeField(auto_now=True, db_index=True)),
                ('email', models.CharField(max_length=300, null=True)),
            ],
        ),
    ]
