# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-09-06 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restcache',
            name='email',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
